# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

project './FanTuanC.xcodeproj'

target 'FanTuanC' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'TZImagePickerController' 
pod 'JPush'
pod 'TTTAttributedLabel'
pod 'SDAutoLayout', '~> 2.1.3'
pod 'YYModel'
pod 'YYText'
pod 'YBAttributeTextTapAction'
pod 'JZNavigationExtension'
pod 'LHPerformanceStatusBar'
pod 'Masonry'
pod 'FMDB'
pod 'ZLPhotoBrowser'
pod 'IFMMenu'
pod 'pop', '~> 1.0'
pod 'BRPickerView', '~> 2.2.1'
pod 'YYWebImage'
pod 'Luban_iOS'
pod 'ATNavigationController'


  # 'node_modules'目录一般位于根目录中
  # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # 如果RN版本 >= 0.45则加入此行
    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # 这个模块是用于调试功能的
    'ART',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTPushNotification',
    'RCTSettings',
    'RCTLinkingIOS',
    # 在这里继续添加你所需要的RN模块
  ]
  # 如果你的RN版本 >= 0.42.0，则加入下面这行
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

   # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'



  target 'FanTuanCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FanTuanCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

